server:
  port: 8080

spring:
  application:
    name: hbase-client
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    root: INFO
    cn.dengdz.hbaseclient: DEBUG

storage:
  config-path: ${user.dir}/.tmp/configs