server:
  port: 34567

spring:
  application:
    name: hbase-client
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

storage:
  config-path: ${user.dir}/.tmp/configs